!include "spline_mod.f90"

program rand_dist 
use spline_mod
implicit none

real,allocatable :: x(:),y(:),y2(:)
character(50) :: inname,outname,LowerLimit,UpperLimit,NumberOfBins
real :: lowlim,uplim,binsize,res
integer :: i,nbins,iostat,N


! CHECK FOR PROPER INPUT FORMAT AT THE TERMINAL, I.E. EITHER THE INPUT FILE HAS TO BE GIVEN, 
   ! IN WHICH CASE THE OUTPUT FILE WILL BE GENERATED BY THE PROGRAM OAND PARAMETERS FOR THE HISTOGRAM
   ! WILL BE CALCULATED AUTOMATICALLY OR PARAMTERES CAN BE EXPLICITELY GIVEN
if (iargc() < 1 .or. iargc() > 4) then 
    print*,'Input format is "./program inputfile" or "./program inputfile LowerLimit UpperLimit NumberOfBins"'
    stop
endif 

call getarg(1,inname)
call getarg(2,LowerLimit)
call getarg(3,UpperLimit)
call getarg(4,NumberOfBins)
read(LowerLimit,*)lowlim
read(UpperLimit,*)uplim
read(NumberOfBins,*)nbins

! OPENING FILES FOR READING 
open(10,file=inname,action='read')  

N = 0 ! NUMBER OF LINES
do    
   read(10,*,iostat=iostat)
   if (iostat < 0) exit
   N=N+1
enddo 

! ALLOCATING THE HISTOGRAM ARRAY
allocate(x(N),y(N),y2(N))  
   
rewind(10)  ! REWINDING FILE FROM EOF TO THE BEGINNING

do i=1,N
    read(10,*)x(i),y(i) 
enddo 

! Calling Spline
call spline(x,y,0.,0.,y2) 

! Calculating Area
call simpsint(lowlim,uplim,N,f,res)
print*, "Area under the curve is:", res

contains


function f(xx)
use spline_mod
implicit none 
real,intent(in) :: xx
real :: f
f = splint(x,y,y2,xx)
end function 



!!Simpson's 1/3 rule integration
subroutine simpsint(a, b, N, f, integral)
implicit none 
real, external :: f 
real,intent(in) :: a,b
real,intent(out) :: integral
integer,intent(in) :: N
real :: h 
integer :: i

h = (b-a)/N
integral = 0.0

do i=1,N
integral = integral + (h/6.0)*( f(a+(i*1.0-1.0)*h) + 4.0*f(a+(i*1.0-.5)*h) + f(a+i*h) )
enddo

return
end subroutine

end program